kind: pipeline
name: testo

clone:
  disable: true

steps:
- name: testo script
  image: archlinux:latest
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
    TELEGRAM_CHAT:
      from_secret: TELEGRAM_CHAT
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
  commands:
    - "export GITHUB_TOKEN"
    - "export BOT_TOKEN"
    - "export $CI_KERNEL_TYPE"
    - "export $CAM_TYPE"
    - pacman -Sy base-devel unzip curl wget zip git --noconfirm
    - "git clone --depth=1 --quiet https://theradcolor:$GITHUB_TOKEN@github.com/theradcolor/snippets -b master"
    - bash snippets/testo